---
- name: Download Docker Image | check istio pilot
  ansible.builtin.stat:
    path: "{{ k3s_path_image }}/istio-pilot-1.23.0.tar"
  register: istiod_image
  changed_when: false

- name: Download Docker Image | save istio pilot
  when: not istiod_image.stat.exists
  ansible.builtin.shell: >
    skopeo copy --insecure-policy
    docker://{{ k3s_download_image_registry }}/istio/pilot:{{ k3s_version_istio }}
    docker-archive:{{ k3s_path_image }}/istio-pilot-{{ k3s_version_istio }}.tar:istio/pilot:{{ k3s_version_istio }}
  args:
    creates: "{{ k3s_path_image }}/istio-pilot-{{ k3s_version_istio }}.tar"

- name: Download Docker Image | check istio proxyv2
  ansible.builtin.stat:
    path: "{{ k3s_path_image }}/istio-proxyv2-{{ k3s_version_istio }}.tar"
  register: istiod_image
  changed_when: false

- name: Download Docker Image | save istio proxyv2
  when: not istiod_image.stat.exists
  ansible.builtin.shell: >
    skopeo copy --insecure-policy
    docker://{{ k3s_download_image_registry }}/istio/proxyv2:{{ k3s_version_istio }}
    docker-archive:{{ k3s_path_image }}/istio-proxyv2-{{ k3s_version_istio }}.tar:istio/proxyv2:{{ k3s_version_istio }}
  args:
    creates: "{{ k3s_path_image }}/istio-proxyv2-{{ k3s_version_istio }}.tar"
