---
- name: Check Metrics Server
  ansible.builtin.stat:
    path: "{{ k3s_download_image }}/metrics-server-v0.7.0.tar"
  register: metricsserver_image
  changed_when: false

- name: Save Metrics Server
  when: not metricsserver_image.stat.exists
  ansible.builtin.shell: >
    skopeo copy --insecure-policy
    docker://{{ k3s_download_image_registry }}/rancher/mirrored-metrics-server:v0.7.0
    docker-archive:{{ k3s_download_image }}/metrics-server-v0.7.0.tar:rancher/mirrored-metrics-server:v0.7.0
  args:
    creates: "{{ k3s_download_image }}/metrics-server-v0.7.0.tar"
