namespace: andreygubarev
name: general
version: 1.0.0

readme: README.md

authors:
  - Andrey Gubarev <andrey@andreygubarev.com> (andreygubarev.com)

description: Collection of useful Ansible roles
license_file: LICENSE

tags:
- infrastructure

dependencies: {}

repository: https://github.com/andreygubarev/ansible-general
documentation: https://github.com/andreygubarev/ansible-general
homepage: https://github.com/andreygubarev/ansible-general
issues: https://github.com/andreygubarev/ansible-general/issues

build_ignore:
  - Makefile
  - .git
  - .gitignore
