namespace: andreygubarev
name: core
version: 1.0.0

readme: README.md

authors:
  - Andrey Gubarev <andrey@andreygubarev.com> (andreygubarev.com)

description: Collection of useful Ansible roles
license_file: LICENSE

tags:
  - infrastructure

dependencies:
  "ansible.posix": ">=1.0.0,<2.0.0"
  "community.crypto": ">=2.0.0,<3.0.0"
  "community.general": ">=8.0.0,<9.0.0"
  "kubernetes.core": ">=2.0.0,<3.0.0"

repository: https://github.com/andreygubarev/ansible-collection-common
documentation: https://github.com/andreygubarev/ansible-collection-common
homepage: https://github.com/andreygubarev/ansible-collection-common
issues: https://github.com/andreygubarev/ansible-collection-common/issues

build_ignore:
  - Makefile
  - .git
  - .gitignore
  - .envrc
  - .yamllint
  - Pipfile
  - Pipfile.lock
