---
- name: Set Skopeo architecture (amd64)
  when: ansible_architecture == 'x86_64'
  ansible.builtin.set_fact:
    skopeo_architecture: amd64

- name: Set Skopeo architecture (arm64)
  when: ansible_architecture == 'aarch64'
  ansible.builtin.set_fact:
    skopeo_architecture: arm64

- name: Check Skopeo SHA256SUM
  ansible.builtin.stat:
    path: "{{ kubernetes_download_cache }}/skopeo.SHA256SUM"
  register: skopeo_checksum

- name: Download Skopeo SHA256SUM
  when: not skopeo_checksum.stat.exists
  ansible.builtin.get_url:
    url: "{{ kubernetes_download_repository }}/github.com/lework/skopeo-binary/releases/download/v{{ kubernetes_version_skopeo }}/skopeo-linux-{{ skopeo_architecture }}.sha256"
    dest: "{{ kubernetes_download_cache }}/skopeo.SHA256SUM"
    mode: 0644
    owner: root
    group: root

- name: Rewrite Skopeo SHA256SUM
  ansible.builtin.replace:
    path: "{{ kubernetes_download_cache }}/skopeo.SHA256SUM"
    regexp: "./bin/skopeo"
    replace: "skopeo"

- name: Check Skopeo
  ansible.builtin.stat:
    path: "{{ kubernetes_download_cache }}/skopeo"
  register: skopeo_binary

- name: Download Skopeo
  when: not skopeo_binary.stat.exists
  ansible.builtin.get_url:
    url: "{{ kubernetes_download_repository }}/github.com/lework/skopeo-binary/releases/download/v{{ kubernetes_version_skopeo }}/skopeo-linux-{{ skopeo_architecture }}"
    checksum: "sha256:file://{{ kubernetes_download_cache }}/skopeo.SHA256SUM"
    dest: "{{ kubernetes_download_cache }}/skopeo"
    mode: 0755
    owner: root
    group: root

- name: Install Skopeo
  ansible.builtin.copy:
    src: "{{ kubernetes_download_cache }}/skopeo"
    remote_src: true
    dest: /usr/local/bin/skopeo
    mode: 0755
    owner: root
    group: root
