---
# Kubernetes
kubernetes_version: 1.30.0
kubernetes_version_apigateway: 1.1.0
kubernetes_version_cilium: 1.15.5
kubernetes_version_ciliumcli: 0.16.7
kubernetes_version_helm: 3.15.0
kubernetes_version_k3s: "v{{ kubernetes_version }}+k3s1"
kubernetes_version_kubectl: "{{ kubernetes_version }}"
kubernetes_version_skopeo: 1.14.3

# Kubernetes | Download
kubernetes_download_cache: "/var/cache/kubernetes"
kubernetes_download_tempdir: "/var/tmp/kubernetes"
kubernetes_download_images: "/var/lib/rancher/k3s/agent/images"
kubernetes_download_repository: "{{ lookup('ansible.builtin.env', 'KUBERNETES_DOWNLOAD_REPOSITORY', default='https:/') }}"

# Kubernetes | Network | Cilium
kubernetes_network_cilium_enabled: true

# Kubernetes | Addons | CoreDNS
kubernetes_addon_coredns_enabled: true

# Kubernetes | Addons | Local Storage
kubernetes_addon_localstorage_enabled: false

# Kubernetes | Addons | Traefik
kubernetes_addon_traefik_enabled: false

# Kubernetes | Addons | Gateway API
kubernetes_addon_gatewayapi_channel: "experimental"

# Kubernetes | Registry
kubernetes_registry: "{{ lookup('ansible.builtin.env', 'KUBERNETES_REGISTRY', default='docker.io') }}"
kubernetes_registry_config: "{{ kubernetes_service_confdir }}/registries.yaml"
kubernetes_registry_embedded_enabled: true

# Kubernetes | Service
kubernetes_service_name: kubernetes
kubernetes_service_enabled: true
kubernetes_service_statedir: /var/lib/rancher/k3s
kubernetes_service_confdir: /etc/rancher/k3s

# Kubernetes | Service | Command
kubernetes_command: /usr/local/bin/k3s

kubernetes_command_args:
  server: >
    {% if kubernetes_node_name != "" %}
    --node-name={{ kubernetes_node_name }}
    {% endif %}
    --private-registry {{ kubernetes_registry_config }}
    --cluster-cidr {{ kubernetes_network_subnet_pods }}
    --service-cidr {{ kubernetes_network_subnet_services }}
    {% if kubernetes_node_external_ip != "" %}
    --node-external-ip={{ kubernetes_node_external_ip }}
    {% endif %}
    --disable-kube-proxy
    --disable-network-policy
    --flannel-backend=none
    {% if kubernetes_network_tailscale_enabled %}
    --vpn-auth="name=tailscale,joinKey={{ kubernetes_network_tailscale_authkey }}"
    {% endif %}
    --data-dir={{ kubernetes_service_statedir }}
    {{ kubernetes_command_extra_args.server }}
  agent: >
    {% if kubernetes_node_name != "" %}
    --node-name={{ kubernetes_node_name }}
    {% endif %}
    --private-registry {{ kubernetes_registry_config }}
    {% if kubernetes_node_external_ip != "" %}
    --node-external-ip={{ kubernetes_node_external_ip }}
    {% endif %}
    {% if kubernetes_network_tailscale_enabled %}
    --vpn-auth="name=tailscale,joinKey={{ kubernetes_network_tailscale_authkey }}"
    {% endif %}
    --data-dir={{ kubernetes_service_statedir }}
    {{ kubernetes_command_extra_args.agent }}

kubernetes_command_extra_args:
  server: ""
  agent: ""
