---
tailscale_enabled: true

tailscale_download_version: "1.66.4"
tailscale_download_dst: "/var/cache/download"
tailscale_download_src:
  amd64: "https://dl.tailscale.com/stable/tailscale_{{ tailscale_download_version }}_amd64.deb"
  arm64: "https://dl.tailscale.com/stable/tailscale_{{ tailscale_download_version }}_arm64.deb"
tailscale_download_checksum:
  amd64: "sha256:be3a20b194101a8d5b84e17802360b718f6545b817e3bf17d5aa52583bc3a36e"
  arm64: "sha256:95f76dc08c489cc08a91b1f1a63fe50630ce92d7cbbfafb0d150db381ad91123"

tailscale_auth_key: ""
tailscale_login_server: ""
tailscale_login_timeout: 30s

tailscale_socket: "/run/tailscale/tailscaled.sock"
