---
tailscale_enabled: true
tailscale_version: "1.66.4"
tailscale_checksum: "5b77a826f64ef73cd3a7daf470e0ff6c6f72e357"

tailscale_auth_key: ""
tailscale_login_server: ""
tailscale_login_timeout: 30s

tailscale_socket: "/run/tailscale/tailscaled.sock"
