---
- name: Check Cilium Operator
  ansible.builtin.stat:
    path: "{{ kubernetes_download_images }}/cilium-operator-v1.15.5.tar"
  register: ciliumoperator_image
  changed_when: false

- name: Save Cilium Operator
  when: not ciliumoperator_image.stat.exists
  ansible.builtin.shell: >
    skopeo copy --insecure-policy
    docker://quay.io/cilium/operator-generic:v1.15.5
    docker-archive:{{ kubernetes_download_images }}/cilium-operator-v1.15.5.tar:quay.io/cilium/operator-generic:v1.15.5
