---
- name: Check Cilium
  ansible.builtin.stat:
    path: "{{ kubernetes_download_cache }}/cilium-v1.15.5.tar"
  register: cilium_image
  changed_when: false

- name: Save Cilium
  when: not cilium_image.stat.exists
  ansible.builtin.shell: >
    skopeo copy --insecure-policy
    docker://quay.io/cilium/cilium:v1.15.5
    oci-archive:{{ kubernetes_download_cache }}/cilium-v1.15.5.tar
