---
- name: Check Metrics Server
  ansible.builtin.stat:
    path: "{{ kubernetes_download_cache }}/metrics-server-v0.7.0.tar"
  register: metricsserver_image
  changed_when: false

- name: Save Metrics Server
  when: not metricsserver_image.stat.exists
  ansible.builtin.shell: >
    skopeo copy --insecure-policy
    docker://docker.io/rancher/mirrored-metrics-server:v0.7.0
    oci-archive:{{ kubernetes_download_cache }}/metrics-server-v0.7.0.tar
