---
driver:
  name: default
platforms:
  - name: instance-1
  - name: instance-2
  - name: instance-3
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_ssh_common_args: >-
          -F /dev/null
          -o ServerAliveCountMax=60
          -o ServerAliveInterval=10
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
        kubernetes_cluster_token: "secret"
        kubernetes_cluster_bootstrap_namespace: "{{ lookup('env', 'PORKBUN_DOMAIN') }}"
        kubernetes_cluster_bootstrap_name: "default"
    host_vars:
      instance-3:
        kubernetes_node_role: "agent"
