---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 60

    - name: Ping
      ansible.builtin.ping:

    - name: Disable IPv6
      become: true
      ansible.posix.sysctl:
        name: "net.ipv6.conf.{{ item }}.disable_ipv6"
        value: 1
        state: present
        sysctl_set: true
      with_items:
        - all
        - default
        - lo

    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - locales-all
          - python3-yaml
        state: present
        update_cache: true
