---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  roles:
    - role: service
      service_provider: porkbun
      service_config:
        domain: svc.cx
