---
- name: Verify porkbun
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  roles:
    - role: service
      service_provider: porkbun
      service_config:
        domain: "{{ lookup('ansible.builtin.env', 'PORKBUN_DOMAIN') }}"
        record:
          name: molecule
          type: A
          data: 1.1.1.1

  post_tasks:
    - name: Assert
      ansible.builtin.assert:
        that:
          - service_status is defined
          - service_status in [True, False]

- name: Verify gandi
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  roles:
    - role: service
      service_provider: gandi
      service_config:
        domain: "{{ lookup('ansible.builtin.env', 'GANDI_DOMAIN') }}"
        record:
          name: molecule
          type: A
          data: 1.1.1.1

  post_tasks:
    - name: Assert
      ansible.builtin.assert:
        that:
          - service_status is defined
          - service_status in [True, False]
