---
- name: Assert configuration | gandi
  ansible.builtin.assert:
    that:
      - dnssd_provider is defined
      - dnssd_provider == 'gandi'

      - dnssd_provider_gandi_token is defined
      - dnssd_provider_gandi_token is string
      - dnssd_provider_gandi_token is match('^[a-zA-Z0-9]{40}$')

      - dnssd_config is defined
      - dnssd_config is mapping

      - dnssd_config['domain'] is defined
      - dnssd_config['domain'] is string
      - dnssd_config['domain'] is match('^[a-z0-9.-]+$')

      - dnssd_config['record'] is defined
      - dnssd_config['record'] is mapping

      - dnssd_config['record']['name'] is defined
      - dnssd_config['record']['name'] is string
      - dnssd_config['record']['name'] is match('^[a-z0-9.-]+$')

      - dnssd_config['record']['type'] is defined
      - dnssd_config['record']['type'] is string
      - dnssd_config['record']['type'] in ['A', 'AAAA', 'CNAME', 'MX', 'TXT', 'SRV', 'NS', 'CAA', 'PTR', 'SOA']

      - dnssd_config['record']['data'] is defined
      - dnssd_config['record']['data'] is string
      - dnssd_config['record']['data'] is match('^[a-z0-9.-]+$')

- name: Register service | gandi
  ansible.builtin.uri:
    url: "https://api.gandi.net/v5/livedns/domains/{{ dnssd_config['domain'] }}/records/{{ dnssd_config['record']['name'] }}"
    method: POST
    headers:
      Authorization: "Bearer {{ dnssd_provider_gandi_token }}"
    body_format: json
    body:
      rrset_name: "{{ dnssd_config['record']['name'] }}"
      rrset_type: "{{ dnssd_config['record']['type'] }}"
      rrset_ttl: "{{ dnssd_ttl }}"
      rrset_values:
        - "{{ dnssd_config['record']['data'] }}"
    status_code:
      - 200
      - 201
      - 409
  register: dnssd_status_gandi

- name: Set service status | gandi
  ansible.builtin.set_fact:
    dnssd_status: "{{ dnssd_status_gandi.status == 201 }}"
