---
- name: Authorize SSH keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  with_items: "{{ ssh_allow_users }}"
  when: item.key is defined
  notify: Restart sshd

- name: Set allow SSH access for users (CIS 5.2.18)
  when: ssh_allow_users | length > 0
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AllowUsers"
    line: "AllowUsers {{ ssh_allow_users | map(attribute='name') | join(' ') }}"
  notify: Restart sshd

- name: Unset allow SSH access for users (CIS 5.2.18)
  when: ssh_allow_users | length == 0
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AllowUsers"
    state: absent
  notify: Restart sshd

- name: Set deny SSH access for users (CIS 5.2.18)
  when: ssh_deny_users | length > 0
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?DenyUsers"
    line: "DenyUsers {{ ssh_deny_users | map(attribute='name') | join(' ') }}"
  notify: Restart sshd

- name: Unset deny SSH access for users (CIS 5.2.18)
  when: ssh_deny_users | length == 0
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?DenyUsers"
    state: absent
  notify: Restart sshd

- name: Set allow SSH access for groups (CIS 5.2.18)
  when: ssh_allow_groups | length > 0
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AllowGroups"
    line: "AllowGroups {{ ssh_allow_groups | map(attribute='name') | join(' ') }}"
  notify: Restart sshd

- name: Unset allow SSH access for groups (CIS 5.2.18)
  when: ssh_allow_groups | length == 0
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AllowGroups"
    state: absent
  notify: Restart sshd

- name: Set deny SSH access for groups (CIS 5.2.18)
  when: ssh_deny_groups | length > 0
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?DenyGroups"
    line: "DenyGroups {{ ssh_deny_groups | map(attribute='name') | join(' ') }}"
  notify: Restart sshd

- name: Unset deny SSH access for groups (CIS 5.2.18)
  when: ssh_deny_groups | length == 0
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?DenyGroups"
    state: absent
  notify: Restart sshd
