---
- name: Install SSHGuard
  when: ssh_sshguard
  ansible.builtin.apt:
    name:
      - sshguard
      - nftables
    state: present
    update_cache: true
    install_recommends: false

- name: Gather SSHGuard service facts
  ansible.builtin.service_facts: {}

- debug:
    var: ansible_facts.services

- name: Start SSHGuard service
  when: ansible_facts.services['sshguard']
  ansible.builtin.systemd_service:
    name: sshguard
    state: started
    enabled: true

- name: Set SSHGuard allowlist
  when: ssh_sshguard_allowlist | length > 0
  ansible.builtin.lineinfile:
    path: /etc/sshguard/whitelist
    line: "{{ item }}"
  with_items: "{{ ssh_sshguard_allowlist }}"
  notify: Restart SSHGuard
