---
- name: Install SSHGuard
  ansible.builtin.apt:
    name:
      - sshguard
      - nftables
    state: present
    update_cache: true
    install_recommends: false

- name: Start SSHGuard service
  ansible.builtin.service:
    name: sshguard
    state: started
    enabled: true

- name: Set SSHGuard allowlist
  when: ssh_sshguard_allowlist | length > 0
  ansible.builtin.lineinfile:
    path: /etc/sshguard/whitelist
    line: "{{ item }}"
  with_items: "{{ ssh_sshguard_allowlist }}"
  notify: Restart SSHGuard
