---
- name: Install OpenSSH server
  ansible.builtin.apt:
    name:
      - openssh-server
    state: present
    update_cache: true

- name: Start OpenSSH service
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true

- name: Enhance OpenSSH security
  when: ssh_hardening
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/001-hardening.yml"

- name: Configure OpenSSH access control
  when: ssh_users | length > 0 or ssh_groups | length > 0
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/002-access-control.yml"
