---
- name: Assert configuration | gandi
  ansible.builtin.assert:
    that:
      - service_provider is defined
      - service_provider == 'gandi'

      - service_config is defined
      - service_config is mapping

      - service_config['domain'] is defined
      - service_config['domain'] is string
      - service_config['domain'] is match('^[a-z0-9.-]+$')

      - service_config['record'] is defined
      - service_config['record'] is mapping

      - service_config['record']['name'] is defined
      - service_config['record']['name'] is string
      - service_config['record']['name'] is match('^[a-z0-9.-]+$')

      - service_config['record']['type'] is defined
      - service_config['record']['type'] is string
      - service_config['record']['type'] in ['A', 'AAAA', 'CNAME', 'MX', 'TXT', 'SRV', 'NS', 'CAA', 'PTR', 'SOA']

      - service_config['record']['data'] is defined
      - service_config['record']['data'] is string
      - service_config['record']['data'] is match('^[a-z0-9.-]+$')

      - service_config['credentials'] is defined
      - service_config['credentials'] is mapping

      - service_config['credentials']['api_token'] is defined
      - service_config['credentials']['api_token'] is string
      - service_config['credentials']['api_token'] is match('^[a-z0-9.-]+$')

- name: Register service | gandi
  ansible.builtin.uri:
    url: "https://api.gandi.net/v5/livedns/domains/{{ service_config['domain'] }}/records/{{ service_config['record']['name'] }}"
    method: POST
    headers:
      Authorization: "Bearer {{ service_config['credentials']['api_token'] }}"
    body_format: json
    body:
      rrset_name: "{{ service_config['record']['name'] }}"
      rrset_type: "{{ service_config['record']['type'] }}"
      rrset_ttl: "{{ service_ttl }}"
      rrset_values:
        - "{{ service_config['record']['data'] }}"
    status_code:
      - 200
      - 201
      - 409
  register: service_status_gandi

- name: Set service status | gandi
  ansible.builtin.set_fact:
    service_status: "{{ service_status_gandi.status == 201 }}"
