Vagrant.configure(2) do |config|
  config.vm.box = case RbConfig::CONFIG["host_cpu"]
    when /amd64/i then "bento/debian-12.5"
    when /arm|aarch64/i then "bento/debian-12.5-arm64"
    else "generic/debian12"
    end

  config.vm.define "molecule-download-1" do |vm1|
    vm1.vm.hostname = "molecule-download-1"
  end

end
