---
- name: Set Cilium architecture (amd64)
  when: ansible_architecture == 'x86_64'
  ansible.builtin.set_fact:
    ciliumcli_architecture: amd64

- name: Set Cilium architecture (arm64)
  when: ansible_architecture == 'aarch64'
  ansible.builtin.set_fact:
    ciliumcli_architecture: arm64

- name: Check Cilium SHA256SUM
  ansible.builtin.stat:
    path: "{{ k3s_path_cache }}/cilium.tar.gz.SHA256SUM"
  register: ciliumcli_checksum

- name: Download Cilium SHA256SUM
  when: not ciliumcli_checksum.stat.exists
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/v{{ k3s_version_ciliumcli }}/cilium-linux-{{ ciliumcli_architecture }}.tar.gz.sha256sum"
    dest: "{{ k3s_path_cache }}/cilium.tar.gz.SHA256SUM"
    tmp_dest: "{{ k3s_path_tmp }}"
    mode: 0644
  register: ciliumcli_checksum_download
  until: ciliumcli_checksum_download is succeeded
  retries: 5
  delay: 5
  timeout: 60

- name: Check Cilium
  ansible.builtin.stat:
    path: "{{ k3s_path_cache }}/cilium.tar.gz"
  register: ciliumcli_binary

- name: Download Cilium
  when: not ciliumcli_binary.stat.exists
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/v{{ k3s_version_ciliumcli }}/cilium-linux-{{ ciliumcli_architecture }}.tar.gz"
    checksum: "sha256:file://{{ k3s_path_cache }}/cilium.tar.gz.SHA256SUM"
    dest: "{{ k3s_path_cache }}/cilium.tar.gz"
    tmp_dest: "{{ k3s_path_tmp }}"
    mode: 0644
  register: ciliumcli_binary_download
  until: ciliumcli_binary_download is succeeded
  retries: 5
  delay: 5
  timeout: 300
