---
- name: Set Helm architecture (amd64)
  when: ansible_architecture == 'x86_64'
  ansible.builtin.set_fact:
    helm_architecture: amd64

- name: Set Helm architecture (arm64)
  when: ansible_architecture == 'aarch64'
  ansible.builtin.set_fact:
    helm_architecture: arm64

- name: Check Helm SHA256SUM
  ansible.builtin.stat:
    path: "{{ k3s_path_cache }}/helm-v{{ k3s_version_helm }}.tar.gz.SHA256SUM"
  register: helm_checksum

- name: Download Helm Checksum
  when: not helm_checksum.stat.exists
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v{{ k3s_version_helm }}-linux-{{ helm_architecture }}.tar.gz.sha256"
    dest: "{{ k3s_path_cache }}/helm-v{{ k3s_version_helm }}.tar.gz.SHA256SUM"
    tmp_dest: "{{ k3s_path_tmp }}"
    mode: 0644
  register: helm_checksum_download
  until: helm_checksum_download is succeeded
  retries: 5
  delay: 5
  timeout: 60

- name: Check Helm
  ansible.builtin.stat:
    path: "{{ k3s_path_cache }}/helm-v{{ k3s_version_helm }}.tar.gz"
  register: helm_binary

- name: Download Helm
  when: not helm_binary.stat.exists
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v{{ k3s_version_helm }}-linux-{{ helm_architecture }}.tar.gz"
    checksum: "sha256:file://{{ k3s_path_cache }}/helm-v{{ k3s_version_helm }}.tar.gz.SHA256SUM"
    dest: "{{ k3s_path_cache }}/helm-v{{ k3s_version_helm }}.tar.gz"
    tmp_dest: "{{ k3s_path_tmp }}"
    mode: 0644
  register: helm_binary_download
  until: helm_binary_download is succeeded
  retries: 5
  delay: 5
  timeout: 300
