---
- name: Set Skopeo architecture (amd64)
  when: ansible_architecture == 'x86_64'
  ansible.builtin.set_fact:
    skopeo_architecture: amd64

- name: Set Skopeo architecture (arm64)
  when: ansible_architecture == 'aarch64'
  ansible.builtin.set_fact:
    skopeo_architecture: arm64

- name: Check Skopeo SHA256SUM
  ansible.builtin.stat:
    path: "{{ k3s_download_cache }}/skopeo.SHA256SUM"
  register: skopeo_checksum

- name: Download Skopeo SHA256SUM
  when: not skopeo_checksum.stat.exists
  ansible.builtin.get_url:
    url: "https://github.com/lework/skopeo-binary/releases/download/v{{ k3s_download_version_skopeo }}/skopeo-linux-{{ skopeo_architecture }}.sha256"
    dest: "{{ k3s_download_cache }}/skopeo.SHA256SUM"
    tmp_dest: "{{ k3s_download_tmp }}"
    mode: 0644
    owner: root
    group: root
  register: skopeo_checksum_download
  until: skopeo_checksum_download is succeeded
  retries: 5
  delay: 5
  timeout: 60

- name: Rewrite Skopeo SHA256SUM
  ansible.builtin.replace:
    path: "{{ k3s_download_cache }}/skopeo.SHA256SUM"
    regexp: "./bin/skopeo"
    replace: "skopeo"

- name: Check Skopeo
  ansible.builtin.stat:
    path: "{{ k3s_download_cache }}/skopeo"
  register: skopeo_binary

- name: Download Skopeo
  when: not skopeo_binary.stat.exists
  ansible.builtin.get_url:
    url: "https://github.com/lework/skopeo-binary/releases/download/v{{ k3s_download_version_skopeo }}/skopeo-linux-{{ skopeo_architecture }}"
    checksum: "sha256:file://{{ k3s_download_cache }}/skopeo.SHA256SUM"
    dest: "{{ k3s_download_cache }}/skopeo"
    tmp_dest: "{{ k3s_download_tmp }}"
    mode: 0755
    owner: root
    group: root
  register: skopeo_binary_download
  until: skopeo_binary_download is succeeded
  retries: 5
  delay: 5
  timeout: 300
