galaxy_info:
  author: Andrey Gubarev <andrey@andreygubarev.com> (andreygubarev.com)
  description: Ansible role to install and configure OpenSSH server.
  company: andreygubarev

  license: MIT

  min_ansible_version: "9.0.0"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - security
    - networking

dependencies: []
