---
- name: Tailscale | wait for readiness
  ansible.builtin.wait_for:
    path: "{{ tailscale_socket }}"
    state: present
    timeout: 60

- name: Tailscale | get status
  ansible.builtin.command: >-
    tailscale
    --socket {{ tailscale_socket }}
    status --json
  register: tailscale_status
  changed_when: false

- name: Tailscale | login
  when: (tailscale_status.stdout | from_json)['BackendState'] == 'NeedsLogin'
  block:
    - name: Tailscale | assert auth key
      ansible.builtin.assert:
        that:
          - tailscale_authkey is defined
          - tailscale_authkey != ""
        success_msg: "Tailscale auth key is defined"
        fail_msg: "Tailscale auth key is not defined"

    - name: Tailscale | login
      ansible.builtin.command: >-
        tailscale
        --socket="{{ tailscale_socket }}"
        up
        --auth-key="{{ tailscale_authkey }}"
        --hostname="{{ ansible_hostname }}"
        {% if tailscale_login_server %}
        --login-server="{{ tailscale_login_server }}"
        {% endif %}
      changed_when: true

- name: Tailscale | enable ip forwarding
  when: tailscale_advertise_exit_node
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    sysctl_set: true
    reload: true
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Tailscale | advertise exit node
  ansible.builtin.command: >-
    tailscale
    --socket {{ tailscale_socket }}
    up
    --hostname {{ ansible_hostname }}
    --advertise-exit-node={{ tailscale_advertise_exit_node | ternary('true', 'false') }}
  changed_when: true
