---
- name: Tailscale | prerequisites
  when: tailscale_install
  ansible.builtin.include_tasks: 000-prerequisite.yml

- name: Tailscale | install
  when: tailscale_install
  ansible.builtin.include_tasks: 010-install.yml

- name: Tailscale | configuration
  when: tailscale_enabled
  block:
    - name: Tailscale | enable systemd service
      ansible.builtin.systemd:
        name: tailscaled
        state: started
        enabled: true

    - name: Tailscale | wait for readiness
      ansible.builtin.wait_for:
        path: "{{ tailscale_socket }}"
        state: present
        timeout: 60

    - name: Tailscale | get status
      ansible.builtin.command: >-
        tailscale
        --socket {{ tailscale_socket }}
        status --json
      register: tailscale_status
      changed_when: false

    - name: Tailscale | login
      when: (tailscale_status.stdout | from_json)['BackendState'] == 'NeedsLogin'
      block:
        - name: Tailscale | assert auth key
          ansible.builtin.assert:
            that:
              - tailscale_authkey is defined
              - tailscale_authkey != ""
            success_msg: "Tailscale auth key is defined"
            fail_msg: "Tailscale auth key is not defined"

        - name: Tailscale | login
          ansible.builtin.command: >-
            tailscale
            --socket {{ tailscale_socket }}
            up
            --hostname {{ ansible_hostname }}
            {% if tailscale_login_server %}
            --login-server {{ tailscale_login_server }}
            {% endif %}
            --timeout {{ tailscale_login_timeout }}
            --auth-key {{ tailscale_authkey }}
          changed_when: true
