---
- name: Ensure cache directory exists
  ansible.builtin.file:
    path: "{{ k3s_path_cache }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure temporary directory exists
  ansible.builtin.file:
    path: "{{ k3s_path_tmp }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download K3S
  ansible.builtin.import_tasks: downloads/k3s.yml

- name: Download Kubectl
  ansible.builtin.import_tasks: downloads/kubectl.yml

- name: Download Helm
  ansible.builtin.import_tasks: downloads/helm.yml

- name: Download Cilium
  ansible.builtin.import_tasks: downloads/cilium.yml

- name: Download Skopeo
  ansible.builtin.import_tasks: downloads/skopeo.yml
