---
- name: Assert configuration
  ansible.builtin.assert:
    that:
      - "k3s_token is defined"
      - "k3s_token is not none"
      - "k3s_token != ''"

- name: Create cluster config
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ k3s_path_confdir }}/config.yaml"
    owner: root
    group: root
    mode: 0644
  register: kubernetes_config

- name: Create cluster registries config
  ansible.builtin.template:
    src: registries.yml.j2
    dest: "{{ k3s_path_confdir }}/registries.yaml"
    owner: root
    group: root
    mode: 0644

- name: Create systemd service environment
  ansible.builtin.template:
    src: k3s.service.env.j2
    dest: "/etc/systemd/system/k3s.service.env"
    owner: root
    group: root
    mode: 0644
  register: k3s_service_env
