---
### Kubernetes State ##########################################################
- name: Ensure state directory
  ansible.builtin.file:
    path: "{{ k3s_path_statedir }}"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Configure Kubernetes addons
  when: k3s_role == 'server'
  ansible.builtin.import_tasks: 051-setup-addons

### Kubernetes Config #########################################################
- name: Assert Kubernetes configuration
  ansible.builtin.assert:
    that:
      - "k3s_token is defined"
      - "k3s_token is not none"
      - "k3s_token != ''"
      - "k3s_role in ['server', 'agent']"

- name: Create Kubernetes configuration directory
  ansible.builtin.file:
    path: "{{ k3s_path_confdir }}/config.yaml.d"
    state: directory
    mode: "0755"

- name: Create Kubernetes configuration
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ k3s_path_confdir }}/config.yaml"
    owner: root
    group: root
    mode: 0644
  register: k3s_state_config

- name: Create Kubernetes configuration for registries
  ansible.builtin.template:
    src: registries.yml.j2
    dest: "{{ k3s_path_confdir }}/registries.yaml"
    owner: root
    group: root
    mode: 0644

- name: Configure Systemd
  ansible.builtin.import_tasks: 052-setup-systemd

- name: Wait for cluster to be ready
  ansible.builtin.wait_for:
    path: "{{ k3s_path_statedir }}/{{ k3s_role }}"

- name: Setup Cilium
  when: k3s_role == 'server' and k3s_server == '127.0.0.1'
  block:
    - name: Initialize Cilium
      ansible.builtin.import_tasks: 060-cilium.yml

    - name: Setup Cilium
      ansible.builtin.import_tasks: 060-cilium.yml
