---
### Kubernetes | Assertions ###################################################
- name: Kubernetes | assert configuration
  ansible.builtin.assert:
    that:
      - "k3s_role in ['server', 'agent']"
      - "k3s_token is defined"
      - "k3s_token is not none"
      - "k3s_token != ''"

### Kubernetes | Node #########################################################
- name: Kubernetes | set node name
  when: k3s_node == ""
  ansible.builtin.set_fact:
    k3s_node: "{{ ansible_facts.hostname }}"

### Kubernetes | State ########################################################
- name: Kubernetes | create state directory
  ansible.builtin.file:
    path: "{{ k3s_path_statedir }}"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | configure addons
  when: k3s_role == 'server'
  ansible.builtin.import_tasks: 051-setup-addons.yml

### Kubernetes | Configuration ################################################
- name: Kubernetes | create configuration directory
  ansible.builtin.file:
    path: "{{ k3s_path_confdir }}/config.yaml.d"
    state: directory
    mode: "0755"

- name: Kubernetes | create configuration for registries
  ansible.builtin.template:
    src: registries.yml.j2
    dest: "{{ k3s_path_confdir }}/registries.yaml"
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | configuration
  ansible.builtin.import_tasks: 052-setup-config.yml

- name: Systemd | create environment file
  ansible.builtin.template:
    src: k3s.service.env.j2
    dest: /etc/systemd/system/k3s.service.env
    owner: root
    group: root
    mode: 0644
  register: k3s_state_env

- name: Systemd | create service
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  register: k3s_state_service

- name: Systemd | service state
  ansible.builtin.import_tasks: 053-setup-systemd.yml

- name: Kubernetes | wait for running state
  ansible.builtin.wait_for:
    path: "{{ k3s_path_statedir }}/{{ k3s_role }}"

- name: Cilium | setup
  when: k3s_role == 'server' and k3s_server == '127.0.0.1'
  block:
    - name: Initialize Cilium
      ansible.builtin.import_tasks: 060-cilium.yml

    - name: Setup Cilium
      ansible.builtin.import_tasks: 060-cilium.yml
