---
- name: Kubernetes | create directory for addons
  ansible.builtin.file:
    path: "{{ k3s_path_statedir }}/server/manifests"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Kubernetes | download gateway api
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v{{ k3s_version_gatewayapi }}/experimental-install.yaml"
    dest: "{{ k3s_path_statedir }}/server/manifests/gatewayapi.yaml"
    owner: root
    group: root
    mode: 0644
