---
- name: Kubernetes | set api server
  when: k3s__present and k3s_apiserver == '127.0.0.1'
  ansible.builtin.set_fact:
    k3s_apiserver: "{{ ansible_default_ipv4.address }}"

- name: Kubernetes | create configuration
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ k3s_path_confdir }}/config.yaml"
    owner: root
    group: root
    mode: 0644
  register: k3s__config
