---
- name: Systemd | get service state
  ansible.builtin.set_fact:
    k3s_state: "{{ 'restarted' if k3s__config.changed or k3s__service.changed or k3s__env.changed or k3s__binary.changed else 'started' }}"

- name: Systemd | set service state
  ansible.builtin.systemd:
    daemon_reload: "{{ k3s__service.changed or k3s__env.changed }}"
    name: k3s
    state: "{{ k3s_state }}"
    enabled: true
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
