---
- name: Cilium | download gateway api
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v{{ k3s_version_apigateway }}/experimental-install.yaml"
    dest: "{{ k3s_path_statedir }}/server/manifests/gatewayapi.yaml"
    owner: root
    group: root
    mode: 0644

- name: Cilium | install gateway api
  ansible.builtin.shell: >
    KUBECONFIG={{ k3s_path_confdir }}/k3s.yaml
    kubectl apply -f {{ k3s_path_statedir }}/server/manifests/gatewayapi.yaml
  changed_when: false

- name: Cilium | add helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Cilium | configure
  ansible.builtin.import_tasks: 061-cilium-config.yml
