---
- name: Cilium | configure gateway api
  ansible.builtin.import_tasks: 061-cilium-gatewayapi.yml

- name: Cilium | set state to installed
  ansible.builtin.set_fact:
    k3s__cilium: true

- name: Cilium | configure
  ansible.builtin.import_tasks: 062-cilium-config.yml
