---
- name: Cilium | configuration
  when: k3s__cilium or k3s_upgrade
  block:
    - name: Cilium | add helm repository
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/

    - name: Cilium | get state
      ansible.builtin.shell: >
        KUBECONFIG={{ k3s_path_confdir }}/k3s.yaml
        kubectl -n kube-system get daemonset cilium
      register: cilium_installed
      changed_when: false
      ignore_errors: true

    - name: Cilium | set api server to remote
      when: cilium_installed.rc == 0
      ansible.builtin.set_fact:
        cilium_apiserver: "{{ k3s_apiserver }}"

    - name: Cilium | set api server to local
      when: cilium_installed.rc != 0
      ansible.builtin.set_fact:
        cilium_apiserver: "127.0.0.1"

    - name: Cilium | setup
      kubernetes.core.helm:
        kubeconfig: "{{ k3s_path_confdir }}/k3s.yaml"
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "{{ k3s_version_cilium }}"
        release_namespace: kube-system
        wait: true
        values:
          k8sServiceHost: "{{ cilium_apiserver }}"
          k8sServicePort: 6443
          image:
            useDigest: false
          operator:
            image:
              useDigest: false
            replicas: 1
          rollOutCiliumPods: true
          ipam:
            operator:
              clusterPoolIPv4PodCIDRList: "{{ k3s_pod_subnet }}"
          kubeProxyReplacement: false
          loadBalancer:
            serviceTopology: true
          # Following configuration allows to expose Gateway resources
          # at the host network using direct exposure of the Envoy proxy
          # to the host ports (including privileged ports).
          nodePort:
            enabled: true
          gatewayAPI:
            enabled: true
            hostNetwork:
              enabled: true
          envoy:
            securityContext:
              capabilities:
                keepCapNetBindService: true
                envoy:
                  - NET_ADMIN
                  - SYS_ADMIN
                  - NET_BIND_SERVICE

    - name: Cilium | wait for readiness
      ansible.builtin.shell: >
        KUBECONFIG={{ k3s_path_confdir }}/k3s.yaml
        kubectl -n kube-system wait --for=condition=ready pod -l app.kubernetes.io/part-of=cilium --timeout=300s
      changed_when: false
