---
- name: Download Binaries
  when: k3s_download or k3s_install
  ansible.builtin.import_tasks: 010-download.yml

- name: Install Binaries
  when: k3s_install
  ansible.builtin.import_tasks: 020-install.yml

- name: Download Docker Images
  when: k3s_download_images or k3s_install
  ansible.builtin.import_tasks: 030-download-images.yml

- name: Configure System
  when: k3s_install
  ansible.builtin.import_tasks: 040-system.yml

- name: Setup Kubernetes
  when: k3s_install
  ansible.builtin.import_tasks: 050-setup.yml
