---
- name: Download Binaries
  when: k3s_install
  ansible.builtin.import_tasks: 010-download.yml

- name: Install Binaries
  when: k3s_install
  ansible.builtin.import_tasks: 020-install.yml

- name: Kubernetes | get state
  ansible.builtin.stat:
    path: "{{ k3s_path_statedir }}/server/node-token"
  register: k3s__present

- name: Kubernetes | set state
  ansible.builtin.set_fact:
    k3s__present: "{{ k3s__present.stat.exists }}"

- name: Download Docker Images
  when: k3s_install and k3s_role == 'server' and not k3s__present
  ansible.builtin.import_tasks: 030-download-images.yml

- name: Kubernetes | install
  when: k3s_install
  block:
    - name: Linux | modify kernel parameters
      ansible.builtin.import_tasks: 040-system.yml

    - name: Kubernetes | set node name
      when: k3s_node == ""
      ansible.builtin.set_fact:
        k3s_node: "{{ ansible_facts.hostname }}"

    - name: Kubernetes | setup
      when: not k3s__present
      block:
        - name: Kubernetes | assert role configuration
          when: k3s_role == 'agent'
          ansible.builtin.assert:
            that:
              - k3s_apiserver != '127.0.0.1'
            msg: "Agent role requires an API server to join"

        - name: Kubernetes | setup
          ansible.builtin.import_tasks: 050-setup.yml

        - name: Kubernetes | wait for readiness
          ansible.builtin.wait_for:
            host: "{{ k3s_apiserver }}"
            port: 6443
            timeout: 90
            state: started

        - name: Istio | setup
          when: k3s_role == 'server'
          ansible.builtin.import_tasks: 060-istio.yml

        - name: Kubernetes | set state to present
          ansible.builtin.set_fact:
            k3s__present: true

    - name: Kubernetes | configure
      when: k3s__present
      block:
        - name: Kubernetes | configuration
          ansible.builtin.import_tasks: 052-setup-config.yml

        - name: Systemd | service state
          ansible.builtin.import_tasks: 053-setup-systemd.yml
