---
- name: Ensure cache directory exists
  ansible.builtin.file:
    path: "{{ kubernetes_download_cache }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure temp directory exists
  ansible.builtin.file:
    path: "{{ kubernetes_download_tempdir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure cache directory exists
  ansible.builtin.file:
    path: "{{ kubernetes_download_images }}"
    state: directory
    mode: 0755
    owner: root
    group: root

### K3S #######################################################################
- name: Download K3S
  ansible.builtin.import_tasks: downloads/k3s.yml

- name: Download Bootstrap
  when: kubernetes_bootstrap_enabled
  block:
    - name: Download kubectl
      ansible.builtin.import_tasks: downloads/kubectl.yml

    - name: Download Helm
      ansible.builtin.import_tasks: downloads/helm.yml

    - name: Download Cilium
      ansible.builtin.import_tasks: downloads/cilium.yml

    - name: Download Skopeo
      ansible.builtin.import_tasks: downloads/skopeo.yml

    - name: Download CoreDNS Image
      ansible.builtin.import_tasks: downloads/images/coredns.yml

    - name: Download Metrics Server Image
      ansible.builtin.import_tasks: downloads/images/metrics-server.yml

    - name: Download Pause Image
      ansible.builtin.import_tasks: downloads/images/pause.yml

    - name: Download Cilium Image
      ansible.builtin.import_tasks: downloads/images/cilium.yml

    - name: Download Cilium Operator Image
      ansible.builtin.import_tasks: downloads/images/cilium-operator.yml
