---
- name: Download K3S (x64)
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ kubernetes_version }}/k3s
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ kubernetes_version }}/sha256sum-amd64.txt
    dest: "{{ kubernetes_command }}"
    owner: root
    group: root
    mode: 0755
  register: kubernetes_binary
  when: ansible_facts.architecture == "x86_64"

- name: Download K3S (arm64)
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ kubernetes_version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ kubernetes_version }}/sha256sum-arm64.txt
    dest: "{{ kubernetes_command }}"
    owner: root
    group: root
    mode: 0755
  register: kubernetes_binary
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")
