---
- name: Register cluster seed status
  ansible.builtin.stat:
    path: "{{ kubernetes_service_statedir }}/server/node-token"
  register: kubernetes_node_running

- name: Set cluster seed status
  ansible.builtin.set_fact:
    kubernetes_node_running: "{{ kubernetes_node_running.stat.exists }}"

- name: Setup cluster seed
  when: not kubernetes_node_running
  block:
    - name: Create manifests directory
      ansible.builtin.file:
        path: "{{ kubernetes_service_statedir }}/server/manifests"
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Disable traefik addon
      ansible.builtin.file:
        path: "{{ kubernetes_service_statedir }}/server/manifests/traefik.yaml.skip"
        state: touch
        owner: root
        group: root
        mode: 0644
      when: not kubernetes_addon_traefik_enabled

    - name: Disable local-storage addon
      ansible.builtin.file:
        path: "{{ kubernetes_service_statedir }}/server/manifests/local-storage.yaml.skip"
        state: touch
        owner: root
        group: root
        mode: 0644
      when: not kubernetes_addon_localstorage_enabled

    - name: Create kube-vip manifest for rbac
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/kube-vip/kube-vip/{{ kubernetes_addon_kubevip_version }}/docs/manifests/rbac.yaml"
        dest: "{{ kubernetes_service_statedir }}/server/manifests/kubevip-rbac.yaml"
        owner: root
        group: root
        mode: 0644
      when: kubernetes_addon_kubevip_enabled

    - name: Create kube-vip manifest for daemonset
      ansible.builtin.template:
        src: "kubevip.yaml.j2"
        dest: "{{ kubernetes_service_statedir }}/server/manifests/kubevip-daemonset.yaml"
        owner: root
        group: root
        mode: 0644
      when: kubernetes_addon_kubevip_enabled

    - name: Setup cluster seed node
      ansible.builtin.import_tasks: 030-setup.yml

- name: Wait for cluster seed endpoint to be ready
  ansible.builtin.wait_for:
    host: "{{ kubernetes_cluster_seed_endpoint }}"
    port: 6443
    timeout: 300
    state: started
