---
- name: Download Gateway API manifest
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v{{ kubernetes_version_apigateway }}/{{ kubernetes_addon_gatewayapi_channel }}-install.yaml"
    dest: "{{ kubernetes_service_statedir }}/server/manifests/gatewayapi.yaml"
    owner: root
    group: root
    mode: 0644

- name: Apply Gateway API manifest
  ansible.builtin.shell: >
    KUBECONFIG={{ kubernetes_service_confdir }}/k3s.yaml
    kubectl apply -f {{ kubernetes_service_statedir }}/server/manifests/gatewayapi.yaml
  changed_when: false

- name: Add Cilium Helm Repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Check whether Cilium is installed
  ansible.builtin.shell: >
    KUBECONFIG={{ kubernetes_service_confdir }}/k3s.yaml
    kubectl -n kube-system get daemonset cilium
  register: cilium_installed
  changed_when: false
  ignore_errors: true

- name: Set Kubernetes Cluster API Server
  when: cilium_installed.rc == 0
  ansible.builtin.set_fact:
    kubernetes_service_host: "{{ lookup('community.general.dig', kubernetes_cluster_apiserver, qtype='A', fail_on_error=true) }}"

- name: Set Kubernetes Cluster API Server to localhost
  when: cilium_installed.rc != 0
  ansible.builtin.set_fact:
    kubernetes_service_host: "127.0.0.1"

- name: Install Cilium
  kubernetes.core.helm:
    kubeconfig: "{{ kubernetes_service_confdir }}/k3s.yaml"
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ kubernetes_network_cilium_version }}"
    release_namespace: kube-system
    wait: true
    values:
      image:
        useDigest: false
      operator:
        image:
          useDigest: false
        replicas: 1
      ipam:
        operator:
          clusterPoolIPv4PodCIDRList: "{{ kubernetes_network_subnet_pods }}"
      loadBalancer:
        serviceTopology: true
      kubeProxyReplacement: true
      gatewayAPI:
        enabled: true
      bpf:
        lbExternalClusterIP: true
      k8sServiceHost: "{{ kubernetes_service_host }}"
      k8sServicePort: 6443

- name: Wait for Cilium to be ready
  ansible.builtin.shell: >
    KUBECONFIG={{ kubernetes_service_confdir }}/k3s.yaml
    kubectl -n kube-system wait --for=condition=ready pod -l app.kubernetes.io/part-of=cilium --timeout=300s
  changed_when: false

- name: Advertise Kubernetes Pods to Tailscale
  when: kubernetes_network_tailscale_enabled
  ansible.builtin.command: >
    tailscale up --advertise-routes={{ kubernetes_network_subnet_pods }}
  changed_when: false
