---
- name: Prerequisite
  ansible.builtin.import_tasks: 000-prerequisite.yml

- name: Download
  ansible.builtin.import_tasks: 010-download.yml

- name: Bootstrap cluster
  when: kubernetes_cluster_bootstrap
  ansible.builtin.import_tasks: 020-bootstrap.yml

- name: Setup cluster
  ansible.builtin.import_tasks: 030-setup.yml
