---
- name: Prerequisite
  ansible.builtin.import_tasks: 000-prerequisite.yml

- name: Download
  ansible.builtin.import_tasks: 010-download.yml

- name: Set node facts
  ansible.builtin.set_fact:
    kubernetes_node_seed: "{{ ansible_hostname == kubernetes_cluster_seed }}"

- name: Setup cluster seed
  ansible.builtin.import_tasks: 020-setup-seed.yml
  when: kubernetes_node_seed

- name: Setup cluster nodes
  ansible.builtin.import_tasks: 030-setup.yml
