---
- name: Prerequisite
  ansible.builtin.import_tasks: 000-prerequisite.yml

- name: Download
  ansible.builtin.import_tasks: 010-download.yml

- name: Bootstrap cluster
  when: kubernetes_cluster_bootstrap
  ansible.builtin.import_tasks: 020-setup.yml

- name: Wait for cluster to be ready
  ansible.builtin.wait_for:
    host: "{{ kubernetes_cluster_apiserver }}"
    port: 6443
    timeout: 300
    state: started

- name: Setup cluster
  ansible.builtin.import_tasks: 020-setup.yml
