---
- name: Restart OpenSSH
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted

- name: Restart SSHGuard
  when: '"sshguard.service" in ansible_facts.services'
  ansible.builtin.systemd_service:
    name: sshguard
    state: "{{ ssh_sshguard | ternary('restarted', 'stopped') }}"
