---
k3s_path_statedir: /var/lib/rancher/k3s
k3s_path_confdir: /etc/rancher/k3s
k3s_path_cache: /var/cache/kubernetes
k3s_path_image: /var/lib/rancher/k3s/agent/images
k3s_path_tmp: /var/tmp/kubernetes

k3s_version_k3s: v1.30.3+k3s1
k3s_version_kubectl: 1.30.3
k3s_version_helm: 3.15.0
k3s_version_ciliumcli: 0.16.7
k3s_version_skopeo: 1.14.3

k3s_download_image_registry: docker.io

k3s_command: /usr/local/bin/k3s
