---
# Kubernetes | Cluster
kubernetes_cluster_name: ""
kubernetes_cluster_token: ""

# Kubernetes | Cluster | Bootstrap
kubernetes_cluster_bootstrap_namespace: ""
kubernetes_cluster_bootstrap_name: "{{ kubernetes_cluster_name }}"

# Kubernetes | Node
kubernetes_node_name: ""
kubernetes_node_role: "server"
kubernetes_node_labels: []
kubernetes_node_external_ip: ""

# Kubernetes | Network
kubernetes_network_subnet_pods: "10.42.0.0/16"
kubernetes_network_subnet_services: "10.43.0.0/16"

# Kubernetes | Network | Tailscale
kubernetes_network_tailscale_enabled: false
kubernetes_network_tailscale_authkey: ""
