---
# Kubernetes | Cluster | Bootstrap
kubernetes_bootstrap_enabled: ""
kubernetes_bootstrap_namespace: "{{ lookup('env', 'KUBERNETES_BOOTSTRAP_NAMESPACE', default='') }}"
kubernetes_bootstrap_name: "{{ lookup('env', 'KUBERNETES_BOOTSTRAP_NAME', default='') }}"
kubernetes_bootstrap_token: "{{ lookup('env', 'KUBERNETES_BOOTSTRAP_TOKEN', default='') }}"

# Kubernetes | Node
kubernetes_node_name: ""
kubernetes_node_role: "server"
kubernetes_node_labels: []
kubernetes_node_external_ip: ""

# Kubernetes | Network
kubernetes_network_subnet_pods: "10.42.0.0/16"
kubernetes_network_subnet_services: "10.43.0.0/16"

# Kubernetes | Network | Tailscale
kubernetes_network_tailscale_enabled: false
kubernetes_network_tailscale_authkey: ""
