---
# Kubernetes | Cluster
kubernetes_cluster_apiserver: "{{ lookup('env', 'KUBERNETES_CLUSTER_APISERVER', default='') }}"
kubernetes_cluster_token: "{{ lookup('env', 'KUBERNETES_CLUSTER_TOKEN', default='') }}"

# Kubernetes | Cluster | Bootstrap
kubernetes_cluster_bootstrap: "{{ lookup('env', 'KUBERNETES_CLUSTER_BOOTSTRAP', default='') }}"

# Kubernetes | Node
kubernetes_node_name: ""
kubernetes_node_role: "server"
kubernetes_node_labels: []
kubernetes_node_external_ip: ""

# Kubernetes | Network
kubernetes_network_subnet_pods: "10.42.0.0/16"
kubernetes_network_subnet_services: "10.43.0.0/16"

# Kubernetes | Network | Tailscale
kubernetes_network_tailscale_enabled: false
kubernetes_network_tailscale_authkey: ""
