---
# Kubernetes
kubernetes_version: v1.30.0+k3s1

# Kubernetes | Cluster
kubernetes_cluster_apiserver: ""
kubernetes_cluster_apitoken: ""
kubernetes_cluster_bootstrap: false
kubernetes_cluster_feature_gates: []

# Kubernetes | Node
kubernetes_node_role: ""
kubernetes_node_labels: []
kubernetes_node_external_ip: ""

# Kubernetes | Addons | CoreDNS
kubernetes_addon_coredns_enabled: true

# Kubernetes | Addons | KubeVIP
kubernetes_addon_kubevip_enabled: false
kubernetes_addon_kubevip_version: v0.6.4
kubernetes_addon_kubevip_address: ""

# Kubernetes | Addons | Local Storage
kubernetes_addon_localstorage_enabled: false

# Kubernetes | Addons | Traefik
kubernetes_addon_traefik_enabled: false

# Kubernetes | Network
kubernetes_network_interface: ""
kubernetes_network_subnet_pods: "10.42.0.0/16"
kubernetes_network_subnet_services: "10.43.0.0/16"

# Kubernetes | Network | Flannel
kubernetes_network_flannel_backend: vxlan

# Kubernetes | Network | Tailscale
kubernetes_network_tailscale_enabled: false
kubernetes_network_tailscale_token: ""

# Kubernetes | Service
kubernetes_service_name: kubernetes
kubernetes_service_enabled: true
kubernetes_service_statedir: /var/lib/rancher/k3s
kubernetes_service_confdir: /etc/rancher/k3s

# Kubernetes | Registry | Embedded
kubernetes_registry_config: "{{ kubernetes_service_confdir }}/registries.yaml"
kubernetes_registry_embedded_enabled: false

# Kubernetes | Service | Command
kubernetes_command: /usr/local/bin/k3s

kubernetes_command_args:
  server: >
    --config {{ kubernetes_service_confdir }}/config.yaml
    --private-registry {{ kubernetes_registry_config }}
    {% for feature_gates in kubernetes_cluster_feature_gates %}
    --kube-apiserver-arg=feature-gates={{ feature_gates }}
    --kube-scheduler-arg=feature-gates={{ feature_gates }}
    --kube-controller-manager-arg=feature-gates={{ feature_gates }}
    --kube-proxy-arg=feature-gates={{ feature_gates }}
    --kubelet-arg=feature-gates={{ feature_gates }}
    {% endfor %}
    --cluster-cidr {{ kubernetes_network_subnet_pods }}
    --service-cidr {{ kubernetes_network_subnet_services }}
    --flannel-backend={{ kubernetes_network_flannel_backend }}
    {% if kubernetes_node_external_ip != "" %}
    --node-external-ip={{ kubernetes_node_external_ip }}
    {% endif %}
    {% if kubernetes_network_interface != "" %}
    --flannel-iface={{ kubernetes_network_interface }}
    {% endif %}
    {% if kubernetes_network_tailscale_enabled %}
    --vpn-auth="name=tailscale,joinKey={{ kubernetes_network_tailscale_token }}"
    {% endif %}
    --data-dir={{ kubernetes_service_statedir }}
    {{ kubernetes_command_extra_args.server }}
  agent: >
    --config {{ kubernetes_service_confdir }}/config.yaml
    --private-registry {{ kubernetes_registry_config }}
    {% for feature_gates in kubernetes_cluster_feature_gates %}
    --kube-proxy-arg=feature-gates={{ feature_gates }}
    --kubelet-arg=feature-gates={{ feature_gates }}
    {% endfor %}
    {% if kubernetes_node_external_ip != "" %}
    --node-external-ip={{ kubernetes_node_external_ip }}
    {% endif %}
    {% if kubernetes_network_interface != "" %}
    --flannel-iface={{ kubernetes_network_interface }}
    {% endif %}
    {% if kubernetes_network_tailscale_enabled %}
    --vpn-auth="name=tailscale,joinKey={{ kubernetes_network_tailscale_token }}"
    {% endif %}
    --data-dir={{ kubernetes_service_statedir }}
    {{ kubernetes_command_extra_args.agent }}

kubernetes_command_extra_args:
  server: ""
  agent: ""


