---
download_src: "{{ lookup('ansible.builtin.env', 'DOWNLOAD_SOURCE', default='') }}"
download_dst: "/var/cache/download"
download_arch: >-
  {%- if ansible_architecture == 'x86_64' -%}
  amd64
  {%- elif ansible_architecture == 'aarch64' -%}
  arm64
  {%- else -%}
  amd64
  {%- endif -%}

### Tailscale #################################################################
download_package_tailscale_enabled: false
download_package_tailscale_version: "1.68.0"
download_package_tailscale_dst: "{{ download_dst }}/tailscale_{{ download_package_tailscale_version }}.deb"
download_package_tailscale_src:
  amd64: "{{ download_src }}/tailscale_{{ download_package_tailscale_version }}_amd64.deb"
  arm64: "{{ download_src }}/tailscale_{{ download_package_tailscale_version }}_arm64.deb"
download_package_tailscale_checksum:
  amd64: "sha256:ed144ec02c916fab6c35febb5898351cff61bf398b7de7184a377051979f0039"
  arm64: "sha256:62d4bf2f20895d37d0b179d1686197e179c5062dd83dfaa885909809733a59f9"
