---
k3s_install: false
k3s_token: ""
k3s_role: server
k3s_server: 127.0.0.1
k3s_download: false
k3s_download_images: false
k3s_sysctl: false
k3s_enable_localstorage: false
k3s_enable_embeddedregistry: true
