---
- name: Assert configuration
  ansible.builtin.assert:
    that:
      - service_provider is defined
      - service_provider in ['gandi', 'porkbun']
      - service_config is defined
      - service_config is mapping

- name: Use service provider
  ansible.builtin.include_tasks: "provider/{{ service_provider }}.yml"

- name: Announce service status
  ansible.builtin.debug:
    msg: "Service status: {{ service_status }}"
