---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Pull images
      ansible.builtin.shell: |
        tart pull {{ item.image }}
      changed_when: false
      loop: "{{ molecule_yml.platforms }}"

    - name: Create instances
      ansible.builtin.shell: |
        tart clone {{ item.image }} {{ item.name }}
        nohup tart run {{ item.name }} --no-graphics --no-audio --no-clipboard &
      args:
        creates: "~/.tart/vms/{{ item.name }}/config.json"
      loop: "{{ molecule_yml.platforms }}"
      register: server_status

    - name: Gather instance IP addresses
      ansible.builtin.command: |
        tart ip {{ item.name }}
      changed_when: false
      loop: "{{ molecule_yml.platforms }}"
      register: server
      until: server is succeeded
      retries: 10
      delay: 1
      ignore_errors: true

    - name: Wait for instances to be ready
      ansible.builtin.wait_for:
        host: "{{ item.stdout }}"
        port: 22
        delay: 5
        timeout: 60
      loop: "{{ server.results }}"

    - name: Create instance config
      when: server_status.changed | default(false) | bool # noqa no-handler
      block:
        - name: Populate instance config dict # noqa jinja
          ansible.builtin.set_fact:
            instance_conf_dict:
              "instance": "{{ item.item.name }}"
              "address": "{{ item.stdout }}"
              "port": "22"
              "user": "admin"
              "password": "admin"
          with_items: "{{ server.results }}"
          register: instance_config_dict

        - name: Convert instance config dict to a list
          ansible.builtin.set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          ansible.builtin.copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"
            mode: "0600"
