---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: instance-1
    groups:
      - kubernetes_server
    image_arch: aarch64
    image_url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS
    vm_cpus: 2
    vm_memory: 2048
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      instance-1:
        kubernetes_node_role: server
        kubernetes_cluster_bootstrap: true
        kubernetes_network_flannel_enabled: false
        kubernetes_network_cilium_enabled: true
    group_vars:
      all:
        kubernetes_cluster_apiserver: "127.0.0.1"
        kubernetes_cluster_apitoken: "secret"

verifier:
  name: testinfra
