---
driver:
  name: default
platforms:
  - name: instance-1
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_ssh_common_args: >-
          -F /dev/null
          -o ServerAliveCountMax=60
          -o ServerAliveInterval=10
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
        kubernetes_cluster_token: "secret"
