---
driver:
  name: default
platforms:
  - name: instance-1
    image: ghcr.io/cirruslabs/debian:latest
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_ssh_common_args: >-
          -F /dev/null
          -o ServerAliveCountMax=60
          -o ServerAliveInterval=10
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
    host_vars:
      instance-1:
        kubernetes_cluster_name: "default"
        kubernetes_cluster_apiserver: "127.0.0.1"
        kubernetes_cluster_apitoken: "secret"
        kubernetes_cluster_bootstrap_domain: "{{ lookup('env', 'GANDI_DOMAIN') }}"
        kubernetes_cluster_bootstrap_token: "{{ lookup('env', 'GANDI_PERSONAL_ACCESS_TOKEN') }}"
