---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 60

    - name: Ping
      ansible.builtin.ping:

    - name: Update cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - locales-all
        state: present
