Vagrant.configure(2) do |config|
  config.vm.box = case RbConfig::CONFIG["host_cpu"]
    when /amd64/i then "bento/debian-12.5"
    when /arm|aarch64/i then "bento/debian-12.5-arm64"
    else "generic/debian12"
    end

  config.vm.define "instance-1" do |vm1|
    vm1.vm.hostname = "instance-1"
  end

  config.vm.define "instance-2" do |vm2|
    vm2.vm.hostname = "instance-2"
  end

  config.vm.define "instance-3" do |vm3|
    vm3.vm.hostname = "instance-3"
  end

end
