# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
  config.vm.provider "vmware_fusion"
  config.vm.box = "bento/debian-12.5-arm64"

  config.vm.define "instance-1" do |vm1|
    vm1.vm.hostname = "instance-1"
  end
end
