---
- name: Setup Kubernetes
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Print Usage
      when: help | default(h) | default(false)
      failed_when: help | default(h) | default(false)
      ansible.builtin.debug:
        msg:
          - "Usage: @andreygubarev/k3s [ROLE] [OPTIONS]"
          - "Roles:"
          - "  server                    Install k3s as a server"
          - "  agent                     Install k3s as an agent"
          - "Options:"
          - "  -i, --install             Install k3s"
          - "  -u, --upgrade             Upgrade k3s"
          - "  --join=IP                 Join a cluster"
          - "  --token=TOKEN             Token for joining a cluster"
          - "  -n, --node=NAME           Set the name of the node"
          - "  -l, --labels=LABELS       Set the labels for the node"
          - "  --enable-localstorage     Enable local storage (default: false)"
          - "  --enable-embeddedregistry Enable embedded registry (default: true)"
          - "  --pod-subnet=SUBNET       Set the pod subnet"
          - "  --service-subnet=SUBNET   Set the service subnet"

    - name: Parse Arguments
      ansible.builtin.set_fact:
        role: "{{ COMMAND }}"
        install: "{{ install | default(i) | default(false) }}"
        upgrade: "{{ upgrade | default(u) | default(false) }}"
        join: "{{ join | default(omit) }}"
        token: "{{ token | default('') }}"
        node: "{{ node | default(n) | default('') }}"
        labels: "{{ labels | default(l) | default([]) }}"
        enable_localstorage: "{{ enable_localstorage | default(false) }}"
        enable_embeddedregistry: "{{ enable_embeddedregistry | default(true) }}"
        pod_subnet: "{{ pod_subnet | default(omit) }}"
        service_subnet: "{{ service_subnet | default(omit) }}"

    - name: Prepare Variables
      ansible.builtin.set_fact:
        k3s_role: "{{ role }}"
        # -n or --node
        k3s_node: "{{ node | default('') }}"
        # -l or --labels
        k3s_labels: "{{ labels | default([]) }}"
        # -i or --install
        k3s_install: "{{ install | default(false) }}"
        # -u or --upgrade
        k3s_upgrade: "{{ upgrade | default(false) }}"
        # --join=127.0.0.1 (default: 127.0.0.1)
        k3s_apiserver: "{{ join | default('127.0.0.1') }}"
        # --token=secret
        k3s_token: "{{ token | default('') }}"
        # --enable-localstorage
        k3s_enable_localstorage: "{{ enable_localstorage | default(false) }}"
        # --enable-embeddedregistry
        k3s_enable_embeddedregistry: "{{ enable_embeddedregistry | default(true) }}"
        # --pod-subnet
        k3s_pod_subnet: "{{ pod_subnet | default(omit) }}"
        # --service-subnet
        k3s_service_subnet: "{{ service_subnet | default(omit) }}"

    - name: Include Role
      ansible.builtin.include_role:
        name: k3s
