---
- name: Setup Kubernetes
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Parse Arguments
      ansible.builtin.set_fact:
        install: "{{ install | default(i) | default(false) }}"
        download: "{{ download | default(false) }}"
        download_images: "{{ download_images | default(false) }}"
        token: "{{ token | default('') }}"

    - name: Prepare Variables
      ansible.builtin.set_fact:
        # -i or --install
        k3s_install: "{{ install | default(false) }}"

        # --download
        k3s_download: "{{ download | default(false) }}"

        # --download-images
        k3s_download_images: "{{ download_images | default(false) }}"

        # --token
        k3s_token: "{{ token | default('') }}"

    - name: Include Role
      ansible.builtin.include_role:
        name: k3s
