---
- name: Setup Kubernetes
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Print Usage
      when: help | default(false)
      ansible.builtin.debug:
        msg: |
          Usage: @andreygubarev/k3s [OPTIONS]

          Options:
            -i, --install             Install k3s
            --role=server|agent       Set the k3s role (default: server)
            --join=IP                 Join a cluster
            --token=TOKEN             Token for joining a cluster
            -n, --node=NAME           Set the name of the node
            --download                Download packages
            --download-images         Download docker images
            --enable-localstorage     Enable local storage
            --enable-embeddedregistry Enable embedded registry
            --pod-subnet=SUBNET       Set the pod subnet
            --service-subnet=SUBNET   Set the service subnet

    - name: Parse Arguments
      failed_when: help | default(false)
      ansible.builtin.set_fact:
        node: "{{ node | default(n) | default('') }}"
        install: "{{ install | default(i) | default(false) }}"
        role: "{{ role | default('server') }}"
        join: "{{ join | default(omit) }}"
        download: "{{ download | default(false) }}"
        download_images: "{{ download_images | default(false) }}"
        token: "{{ token | default('') }}"
        sysctl: "{{ sysctl | default(false) }}"
        enable_localstorage: "{{ enable_localstorage | default(false) }}"
        enable_embeddedregistry: "{{ enable_embeddedregistry | default(true) }}"
        pod_subnet: "{{ pod_subnet | default(omit) }}"
        service_subnet: "{{ service_subnet | default(omit) }}"

    - name: Prepare Variables
      ansible.builtin.set_fact:
        # -n or --node
        k3s_node: "{{ node | default('') }}"
        # -i or --install
        k3s_install: "{{ install | default(false) }}"
        # --role=server or --role=agent (default: server)
        k3s_role: "{{ role | default('server') }}"
        # --join=127.0.0.1 (default: 127.0.0.1)
        k3s_server: "{{ join | default('127.0.0.1') }}"
        # --token=secret
        k3s_token: "{{ token | default('') }}"
        # --download
        k3s_download: "{{ download | default(false) }}"
        # --download-images
        k3s_download_images: "{{ download_images | default(false) }}"
        # --enable-localstorage
        k3s_enable_localstorage: "{{ enable_localstorage | default(false) }}"
        # --enable-embeddedregistry
        k3s_enable_embeddedregistry: "{{ enable_embeddedregistry | default(true) }}"
        # --pod-subnet
        k3s_pod_subnet: "{{ pod_subnet | default(omit) }}"
        # --service-subnet
        k3s_service_subnet: "{{ service_subnet | default(omit) }}"

    - name: Include Role
      ansible.builtin.include_role:
        name: k3s
