---
- name: Setup TailScale
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  roles:
    - role: download
      vars:
        download_package_tailscale_enabled: true

    - role: tailscale
