---
- name: Setup SSH server
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  roles:
    - role: ssh
      vars:
        # --install
        ssh_openssh: "{{ install | default(false) }}"

        # --enable-sshguard
        ssh_sshguard: "{{ enable_sshguard | default(false) }}"

        # --enable-hardening
        ssh_hardening: "{{ enable_hardening | default(false) }}"

        # --enable-tcp-forwarding
        ssh_hardening_allow_tcp_forwarding: "{{ enable_tcp_forwarding | default(false) }}"

        # --user=andrey:andreygubarev
        ssh_users: >-
          {%- if user is defined and user is string and user | length > 0 -%}
          [dict(["name", "key"] | zip(user | split(':'))) | combine({"state": "allow"})]
          {%- else -%}
          []
          {%- endif -%}

        # ssh_users:
        #   - name: user1
        #     state: allow
        #     key: https://github.com/user1.keys
        #   - name: user2
        #     state: deny
        #     key: https://github.com/user2.keys

        ssh_groups: []
        # ssh_groups:
        #   - name: group1
        #     state: allow
        #   - name: group2
        #     state: deny
