---
- name: Setup SSH server
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  pre_tasks:
    - name: Prepare variables
      ansible.builtin.set_fact:
        # --install
        ssh_openssh: "{{ install | default(false) }}"

        # --enable-sshguard
        ssh_sshguard: "{{ enable_sshguard | default(false) }}"

        # --enable-hardening
        ssh_hardening: "{{ enable_hardening | default(false) }}"

        # --enable-tcp-forwarding
        ssh_hardening_allow_tcp_forwarding: "{{ enable_tcp_forwarding | default(false) }}"

        # --user=andrey:andreygubarev
        ssh_users: >-
          {%- if user is defined and user is string and user | length > 0 -%}
          {{ [dict(["name", "key"] | zip(user | split(':'))) | combine({"state": "allow"})] }}
          {%- else -%}
          {{ [] }}
          {%- endif -%}

        # --group=group1
        ssh_groups: >-
          {%- if group is defined and group is string and group | length > 0 -%}
          {{ [dict(["name"] | zip([group])) | combine({"state": "allow"})] }}
          {%- else -%}
          {{ [] }}
          {%- endif -%}

  roles:
    - role: ssh
